// Generated by generate_config.sh - do not edit by hand
window.DASHBOARD_CONFIG = {
  region: "us-east-1",
  userPoolId: "us-east-1_yiVCjIS7Y",
  clientId: "3m4l310k23rel458ma377a6lj6",
  appsyncHttp: "https://wwull7zx3ffofbi4uwaek7n4fa.appsync-api.us-east-1.amazonaws.com/event",
  appsyncRealtime: "wss://wwull7zx3ffofbi4uwaek7n4fa.appsync-realtime-api.us-east-1.amazonaws.com/event/realtime",
  agentArn: "arn:aws:bedrock-agentcore:us-east-1:123456789012:runtime/DynamoCacheTravelAgent-y54nEU2dnF",
  planCacheArn: "arn:aws:bedrock-agentcore:us-east-1:123456789012:runtime/DynamoPlanCacheAgent-MiVJMADBDj",
};
