#!/usr/bin/env bash
# Generate config.js for the DynamoDB-cache dashboard.
# Run before build/deploy. Uses /dynamodb-cache/* SSM params.
set -euo pipefail
cd "$(dirname "$0")"

REGION="${AWS_REGION:-us-east-1}"

param() { AWS_PROFILE="${AWS_PROFILE:-default}" aws ssm get-parameter --name "$1" --region "$REGION" --query "Parameter.Value" --output text; }

POOL_ID=$(param /dynamodb-cache/auth/user_pool_id)
CLIENT_ID=$(param /dynamodb-cache/auth/web_client_id)
HTTP_ENDPOINT=$(param /dynamodb-cache/appsync/http_endpoint)
AGENT_ARN=$(param /dynamodb-cache/agent-runtime-arn)
PLAN_ARN=$(param /dynamodb-cache/plan-cache-runtime-arn)

cat > config.js <<EOF
// Generated by generate_config.sh - do not edit by hand
window.DASHBOARD_CONFIG = {
  region: "$REGION",
  userPoolId: "$POOL_ID",
  clientId: "$CLIENT_ID",
  appsyncHttp: "https://$HTTP_ENDPOINT/event",
  appsyncRealtime: "wss://${HTTP_ENDPOINT/appsync-api/appsync-realtime-api}/event/realtime",
  agentArn: "$AGENT_ARN",
  planCacheArn: "$PLAN_ARN",
};
EOF
echo "config.js written:"
cat config.js
