#!/usr/bin/env bash
# Generate config.js for the dashboard from the SSM cross-stack contract
# and the backend stack's Cognito resources. Run before build/deploy.
set -euo pipefail
cd "$(dirname "$0")"

REGION="${AWS_REGION:-us-east-1}"
STACK="SemanticCacheWebBackendStack"

param() { aws ssm get-parameter --name "$1" --region "$REGION" --query "Parameter.Value" --output text; }

POOL_ID=$(aws cloudformation describe-stack-resources --stack-name "$STACK" --region "$REGION" \
  --query "StackResources[?ResourceType=='AWS::Cognito::UserPool'].PhysicalResourceId | [0]" --output text)
CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id "$POOL_ID" --region "$REGION" \
  --query "UserPoolClients[0].ClientId" --output text)
HTTP_ENDPOINT=$(param /semantic-cache/appsync/http_endpoint)
AGENT_ARN=$(param /semantic-cache/agent-runtime-arn)
PLAN_ARN=$(param /semantic-cache/plan-cache-runtime-arn)
STRATEGY_ARN=$(param /semantic-cache/strategy-memory-runtime-arn)
SKILL_ARN=$(param /semantic-cache/skill-induction-runtime-arn)

cat > config.js <<EOF
// Generated by generate_config.sh — do not edit by hand
window.DASHBOARD_CONFIG = {
  region: "$REGION",
  userPoolId: "$POOL_ID",
  clientId: "$CLIENT_ID",
  appsyncHttp: "https://$HTTP_ENDPOINT/event",
  appsyncRealtime: "wss://${HTTP_ENDPOINT/appsync-api/appsync-realtime-api}/event/realtime",
  agentArn: "$AGENT_ARN",
  planCacheArn: "$PLAN_ARN",
  strategyMemoryArn: "$STRATEGY_ARN",
  skillInductionArn: "$SKILL_ARN",
};
EOF
echo "config.js written:"
cat config.js
