"""Semantic response cache on ElastiCache for Valkey vector search.

Dual-key layout keeps large answer payloads out of the HNSW index:
    semcache:vec:<id>  HASH indexed by FT: embedding (FLOAT32), model TAG, tokens
    semcache:ans:<id>  HASH payload: question, answer, token usage

The cache fails open: any Valkey or embedding error means "miss" and the
agent runs normally.
"""

import json
import logging
import random
import time
import uuid

from valkey.exceptions import ResponseError

from embeddings import VECTOR_DIM, embedding_to_bytes, generate_embedding

logger = logging.getLogger(__name__)

INDEX_NAME = "idx:semcache"
PREFIX_VECTOR = "semcache:vec:"
PREFIX_ANSWER = "semcache:ans:"


def supports_ft_search(client) -> bool:
    """Probe with FT._LIST — reliable regardless of reported engine version."""
    try:
        client.execute_command("FT._LIST")
        return True
    except ResponseError:
        return False


def ensure_index(client) -> None:
    """Create the HNSW COSINE index once. Safe to call on every cold start."""
    try:
        client.execute_command(
            "FT.CREATE", INDEX_NAME,
            "ON", "HASH",
            "PREFIX", "1", PREFIX_VECTOR,
            "SCHEMA",
            "embedding", "VECTOR", "HNSW", "6",
                "TYPE", "FLOAT32",
                "DIM", str(VECTOR_DIM),
                "DISTANCE_METRIC", "COSINE",
            "model", "TAG",
        )
    except ResponseError as e:
        if "already exists" not in str(e).lower():
            raise


def _escape_tag(value: str) -> str:
    return value.replace("-", "\\-").replace(".", "\\.").replace(":", "\\:")


class SemanticCache:
    def __init__(self, client, model_id: str, threshold: float, ttl: int):
        self.client = client
        self.model_id = model_id
        self.threshold = threshold
        self.ttl = ttl

    def lookup(self, question: str) -> dict | None:
        """Return {answer, similarity, tokens_saved} on a hit, else None.

        Pre-filters by model TAG so an answer generated by one model is
        never served for another.
        """
        try:
            query_vec = embedding_to_bytes(generate_embedding(question))
            result = self.client.execute_command(
                "FT.SEARCH", INDEX_NAME,
                f"(@model:{{{_escape_tag(self.model_id)}}})"
                "=>[KNN 1 @embedding $vec AS score]",
                "PARAMS", "2", "vec", query_vec,
                "RETURN", "2", "entry_id", "score",
                "DIALECT", "2",
            )
        except Exception:
            logger.exception("cache lookup failed, treating as miss")
            return None

        if not result or int(result[0]) == 0:
            return None

        fields = result[2]
        doc = {}
        for i in range(0, len(fields), 2):
            key = fields[i].decode() if isinstance(fields[i], bytes) else fields[i]
            val = fields[i + 1].decode() if isinstance(fields[i + 1], bytes) else fields[i + 1]
            doc[key] = val

        # FT.SEARCH returns cosine DISTANCE (0 identical, 2 opposite).
        similarity = 1.0 - (float(doc["score"]) / 2.0)
        if similarity < self.threshold:
            # Log near-misses so the threshold can be tuned from real traffic.
            logger.info(json.dumps({
                "cache_miss_best_similarity": round(similarity, 4),
                "threshold": self.threshold,
            }))
            return None

        answer_data = self.client.hgetall(f"{PREFIX_ANSWER}{doc['entry_id']}")
        if not answer_data:
            return None

        return {
            "answer": answer_data[b"answer"].decode(),
            "similarity": round(similarity, 4),
            "tokens_saved": int(answer_data.get(b"total_tokens", b"0")),
        }

    def store(self, question: str, answer: str, usage: dict) -> None:
        """Persist a fresh answer. Failures are logged, never raised."""
        try:
            entry_id = str(uuid.uuid4())
            embedding = embedding_to_bytes(generate_embedding(question))

            self.client.hset(f"{PREFIX_VECTOR}{entry_id}", mapping={
                "embedding": embedding,
                "entry_id": entry_id,
                "model": self.model_id,
                "timestamp": str(time.time()),
            })
            self.client.hset(f"{PREFIX_ANSWER}{entry_id}", mapping={
                "question": question,
                "answer": answer,
                "input_tokens": str(usage.get("inputTokens", 0)),
                "output_tokens": str(usage.get("outputTokens", 0)),
                "total_tokens": str(usage.get("totalTokens", 0)),
            })

            # Jitter spreads expirations so many entries never expire at once.
            ttl = self.ttl + random.randint(0, max(1, self.ttl // 10))
            self.client.expire(f"{PREFIX_VECTOR}{entry_id}", ttl)
            self.client.expire(f"{PREFIX_ANSWER}{entry_id}", ttl)
        except Exception:
            logger.exception("cache store failed, answer not cached")
