"""Semantic response cache on ElastiCache for Valkey vector search.

Dual-key layout keeps large answer payloads out of the HNSW index:
    semcache:vec:<id>  HASH indexed by FT: embedding (FLOAT32), model TAG, tokens
    semcache:ans:<id>  HASH payload: question, answer, token usage

The cache fails open: any Valkey or embedding error means "miss" and the
agent runs normally.
"""

import json
import logging
import random
import time
import uuid

from valkey.exceptions import ResponseError

from embeddings import VECTOR_DIM, embedding_to_bytes, generate_embedding

logger = logging.getLogger(__name__)

INDEX_NAME = "idx:semcache"
PREFIX_VECTOR = "semcache:vec:"
PREFIX_ANSWER = "semcache:ans:"


def supports_ft_search(client) -> bool:
    """Probe with FT._LIST — reliable regardless of reported engine version."""
    try:
        client.execute_command("FT._LIST")
        return True
    except ResponseError:
        return False


def ensure_index(client) -> None:
    """Create the HNSW COSINE index once. Safe to call on every cold start."""
    try:
        client.execute_command(
            "FT.CREATE", INDEX_NAME,
            "ON", "HASH",
            "PREFIX", "1", PREFIX_VECTOR,
            "SCHEMA",
            "embedding", "VECTOR", "HNSW", "6",
                "TYPE", "FLOAT32",
                "DIM", str(VECTOR_DIM),
                "DISTANCE_METRIC", "COSINE",
            "model", "TAG",
        )
    except ResponseError as e:
        if "already exists" not in str(e).lower():
            raise


def _escape_tag(value: str) -> str:
    return value.replace("-", "\\-").replace(".", "\\.").replace(":", "\\:")


def _critical_params(text: str) -> set:
    """B5/B2 guard — extract parameters that MUST match exactly for a cached
    answer to be valid: dates and numbers. Embeddings score "flights on
    2026-09-15" vs "flights on 2026-12-15" at ~0.97 (measured with our
    calibration harness), so similarity alone can never separate them; the
    temporal-caching literature calls this out as the primary semantic-cache
    failure mode (arXiv:2605.20630)."""
    import re

    params = set(re.findall(r"\d{4}-\d{2}-\d{2}", text))          # ISO dates
    params.update(re.findall(r"\b\d{1,2}/\d{1,2}(?:/\d{2,4})?\b", text))
    params.update(re.findall(r"\b\d+\b", text))                   # bare numbers
    return params


class SemanticCache:
    def __init__(self, client, model_id: str, threshold: float, ttl: int,
                 prompt_hash: str = ""):
        self.client = client
        self.model_id = model_id
        self.threshold = threshold
        self.ttl = ttl
        # Stored WITH each entry (not in the lookup filter): a hit under a
        # different prompt is still served — rewritten, never discarded.
        self.prompt_hash = prompt_hash

    def lookup(self, question: str) -> dict | None:
        """Return {answer, similarity, tokens_saved} on a hit, else None.

        Pre-filters by model TAG so an answer generated by one model is
        never served for another.
        """
        try:
            query_vec = embedding_to_bytes(generate_embedding(question))
            result = self.client.execute_command(
                "FT.SEARCH", INDEX_NAME,
                f"(@model:{{{_escape_tag(self.model_id)}}})"
                "=>[KNN 1 @embedding $vec AS score]",
                "PARAMS", "2", "vec", query_vec,
                "RETURN", "2", "entry_id", "score",
                "DIALECT", "2",
            )
        except Exception:
            logger.exception("cache lookup failed, treating as miss")
            return None

        if not result or int(result[0]) == 0:
            return None

        fields = result[2]
        doc = {}
        for i in range(0, len(fields), 2):
            key = fields[i].decode() if isinstance(fields[i], bytes) else fields[i]
            val = fields[i + 1].decode() if isinstance(fields[i + 1], bytes) else fields[i + 1]
            doc[key] = val

        # FT.SEARCH returns cosine DISTANCE (0 identical, 2 opposite).
        similarity = 1.0 - (float(doc["score"]) / 2.0)
        if similarity < self.threshold:
            # Log near-misses so the threshold can be tuned from real traffic.
            logger.info(json.dumps({
                "cache_miss_best_similarity": round(similarity, 4),
                "threshold": self.threshold,
            }))
            # B1 — expose the near-miss candidate (within 0.10 of the
            # threshold) so the caller can verify-and-promote it AFTER
            # generating the fresh answer (off the user's critical path).
            if similarity >= self.threshold - 0.10:
                self._last_near_miss = {
                    "entry_id": doc["entry_id"],
                    "similarity": round(similarity, 4),
                }
            else:
                self._last_near_miss = None
            return None
        self._last_near_miss = None

        answer_data = self.client.hgetall(f"{PREFIX_ANSWER}{doc['entry_id']}")
        if not answer_data:
            return None

        # Critical-parameter guard: dates/numbers must match EXACTLY even on
        # a high-similarity hit ("Sept 15 flights" ≠ "Dec 15 flights" at 0.97
        # cosine). Mismatch = treat as miss.
        cached_question = answer_data.get(b"question", b"").decode()
        if _critical_params(question) != _critical_params(cached_question):
            logger.info(json.dumps({
                "cache_param_mismatch": True,
                "similarity": round(similarity, 4),
            }))
            self._last_near_miss = None
            return None

        return {
            "answer": answer_data[b"answer"].decode(),
            "similarity": round(similarity, 4),
            "tokens_saved": int(answer_data.get(b"total_tokens", b"0")),
            "entry_id": doc["entry_id"],
            # True when the entry was generated under the CURRENT prompt;
            # False means the caller should rewrite before serving.
            "prompt_current": (
                answer_data.get(b"prompt_hash", b"").decode() == self.prompt_hash
            ),
        }

    @property
    def near_miss(self) -> dict | None:
        """The candidate just below the threshold from the last lookup."""
        return getattr(self, "_last_near_miss", None)

    def promote_near_miss(self, question: str, fresh_answer: str) -> bool:
        """B1 — verified promotion (Krites pattern, arXiv:2602.13165, adapted
        for Lambda): the near-miss candidate is verified by comparing the
        FRESH answer against the cached one via embeddings. If they agree,
        this question's vector is stored as an alias pointing to the SAME
        answer entry, so future paraphrases in this band become hits.
        Runs after the user already has their answer — no hot-path cost."""
        candidate = self.near_miss
        if not candidate:
            return False
        try:
            cached = self.client.hgetall(f"{PREFIX_ANSWER}{candidate['entry_id']}")
            if not cached:
                return False
            cached_answer = cached[b"answer"].decode()
            vec_a = generate_embedding(fresh_answer[:1500])
            vec_b = generate_embedding(cached_answer[:1500])
            dot = sum(x * y for x, y in zip(vec_a, vec_b))
            norm = (sum(x * x for x in vec_a) ** 0.5) * (sum(y * y for y in vec_b) ** 0.5)
            agreement = dot / norm if norm else 0.0
            if agreement < 0.90:
                return False
            alias_id = str(uuid.uuid4())
            self.client.hset(f"{PREFIX_VECTOR}{alias_id}", mapping={
                "embedding": embedding_to_bytes(generate_embedding(question)),
                "entry_id": candidate["entry_id"],  # alias -> existing answer
                "model": self.model_id,
                "timestamp": str(time.time()),
            })
            self.client.expire(f"{PREFIX_VECTOR}{alias_id}", self.ttl)
            logger.info(json.dumps({
                "near_miss_promoted": True,
                "similarity": candidate["similarity"],
                "answer_agreement": round(agreement, 4),
            }))
            return True
        except Exception:
            logger.exception("near-miss promotion failed")
            return False

    def refresh(self, entry_id: str, answer: str) -> None:
        """Self-healing: replace an entry's answer with its rewrite under the
        current prompt, so the next hit is verbatim again."""
        try:
            self.client.hset(f"{PREFIX_ANSWER}{entry_id}", mapping={
                "answer": answer,
                "prompt_hash": self.prompt_hash,
            })
        except Exception:
            logger.exception("cache refresh failed")

    def store(self, question: str, answer: str, usage: dict) -> None:
        """Persist a fresh answer. Failures are logged, never raised."""
        try:
            entry_id = str(uuid.uuid4())
            embedding = embedding_to_bytes(generate_embedding(question))
            prompt_hash = self.prompt_hash

            self.client.hset(f"{PREFIX_VECTOR}{entry_id}", mapping={
                "embedding": embedding,
                "entry_id": entry_id,
                "model": self.model_id,
                "timestamp": str(time.time()),
            })
            self.client.hset(f"{PREFIX_ANSWER}{entry_id}", mapping={
                "question": question,
                "answer": answer,
                "prompt_hash": prompt_hash,
                "input_tokens": str(usage.get("inputTokens", 0)),
                "output_tokens": str(usage.get("outputTokens", 0)),
                "total_tokens": str(usage.get("totalTokens", 0)),
            })

            # Jitter spreads expirations so many entries never expire at once.
            ttl = self.ttl + random.randint(0, max(1, self.ttl // 10))  # nosec B311 - random only for TTL jitter, not security
            self.client.expire(f"{PREFIX_VECTOR}{entry_id}", ttl)
            self.client.expire(f"{PREFIX_ANSWER}{entry_id}", ttl)
        except Exception:
            logger.exception("cache store failed, answer not cached")
