import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { ChatService, ChatServiceError } from './chatService';
import type { AppSyncEventsService } from './appSyncEventsService';

/**
 * Feature: chat-persistence, Property 1: Round-trip de serialización de payloads CRUD
 *
 * **Validates: Requirements 1.7**
 *
 * For any valid CRUD action payload (with fields `action`, `user_id`, and optional
 * parameters like `conversation_id`, `title`, `limit`, `next_token`), serializing
 * to JSON with `JSON.stringify` and then deserializing with `JSON.parse` must produce
 * an object with exactly the same fields and values as the original.
 */

/** Arbitrary for the CRUD action field */
const actionArb = fc.constantFrom(
  'list_conversations',
  'get_messages',
  'create_conversation',
  'update_conversation',
  'delete_conversation',
);

/** Arbitrary for a non-empty user_id string */
const userIdArb = fc.string({ minLength: 1 }).filter((s) => s.trim().length > 0);

/** Arbitrary for a UUID v4 string (conversation_id) */
const uuidV4Arb = fc.uuid().filter((u) => /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(u));

/** Arbitrary for a positive integer (limit) */
const limitArb = fc.integer({ min: 1, max: 1000 });

/** Arbitrary for next_token (string or null) */
const nextTokenArb = fc.oneof(
  fc.string({ minLength: 1 }),
  fc.constant(null),
);

/** Arbitrary for a CRUD payload with required and optional fields */
const crudPayloadArb = fc.record(
  {
    action: actionArb,
    user_id: userIdArb,
    conversation_id: uuidV4Arb,
    title: fc.string(),
    limit: limitArb,
    next_token: nextTokenArb,
  },
  {
    requiredKeys: ['action', 'user_id'],
  },
);

describe('Feature: chat-persistence, Property 1: Round-trip de serialización de payloads CRUD', () => {
  it('JSON.parse(JSON.stringify(payload)) produces an identical object for any CRUD payload', () => {
    fc.assert(
      fc.property(crudPayloadArb, (payload) => {
        const serialized = JSON.stringify(payload);
        const deserialized = JSON.parse(serialized);

        // Verify deep equality — all fields and values must match
        expect(deserialized).toEqual(payload);

        // Verify the same keys are present
        expect(Object.keys(deserialized).sort()).toEqual(Object.keys(payload).sort());

        // Verify action field is preserved exactly
        expect(deserialized.action).toBe(payload.action);

        // Verify user_id field is preserved exactly
        expect(deserialized.user_id).toBe(payload.user_id);

        // Verify optional fields when present
        if ('conversation_id' in payload) {
          expect(deserialized.conversation_id).toBe(payload.conversation_id);
        }
        if ('title' in payload) {
          expect(deserialized.title).toBe(payload.title);
        }
        if ('limit' in payload) {
          expect(deserialized.limit).toBe(payload.limit);
        }
        if ('next_token' in payload) {
          expect(deserialized.next_token).toBe(payload.next_token);
        }
      }),
      { numRuns: 100 },
    );
  });
});

/**
 * Feature: chat-persistence, Property 2: Formato UUID v4 de Conversation IDs
 *
 * **Validates: Requirements 2.1, 2.3**
 *
 * For any conversation ID generated by `crypto.randomUUID()`, the value must
 * match the UUID v4 regex pattern:
 * ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
 */

const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

describe('Feature: chat-persistence, Property 2: Formato UUID v4 de Conversation IDs', () => {
  it('crypto.randomUUID() always produces a valid UUID v4 string', () => {
    fc.assert(
      fc.property(fc.integer(), (_seed) => {
        const uuid = crypto.randomUUID();

        // Must be a string
        expect(typeof uuid).toBe('string');

        // Must match UUID v4 regex pattern
        expect(uuid).toMatch(UUID_V4_REGEX);

        // Version digit (position 14) must be '4'
        expect(uuid[14]).toBe('4');

        // Variant digit (position 19) must be one of '8', '9', 'a', 'b'
        expect(['8', '9', 'a', 'b']).toContain(uuid[19]);

        // Must have exactly 36 characters (32 hex + 4 dashes)
        expect(uuid.length).toBe(36);

        // Must have dashes at correct positions
        expect(uuid[8]).toBe('-');
        expect(uuid[13]).toBe('-');
        expect(uuid[18]).toBe('-');
        expect(uuid[23]).toBe('-');
      }),
      { numRuns: 100 },
    );
  });
});


/**
 * Feature: chat-persistence, Property 5: Round-trip de conversión de fechas UTC
 *
 * **Validates: Requirements 6.6, 9.1, 9.4**
 *
 * For any valid UTC ISO 8601 date string, converting it to a `Date` object with
 * `new Date(utcString)` and then calling `.toISOString()` must preserve the temporal
 * information without loss. Equivalently, the epoch timestamp obtained via `.getTime()`
 * must be identical when reconstructing the Date from the ISO string.
 */

/** Arbitrary that generates valid UTC ISO 8601 date strings using fc.date() */
const utcDateStringArb = fc.date({
  min: new Date('1970-01-01T00:00:00.000Z'),
  max: new Date('2099-12-31T23:59:59.999Z'),
  noInvalidDate: true,
}).map((d) => d.toISOString());

describe('Feature: chat-persistence, Property 5: Round-trip de conversión de fechas UTC', () => {
  it('new Date(utcString).toISOString() preserves the original UTC ISO 8601 string', () => {
    fc.assert(
      fc.property(utcDateStringArb, (utcString) => {
        const date = new Date(utcString);

        // The Date object must be valid (not NaN)
        expect(date.getTime()).not.toBeNaN();

        // Round-trip: toISOString() must produce the exact same string
        expect(date.toISOString()).toBe(utcString);

        // Epoch timestamp must be identical when reconstructing from the ISO string
        const reconstructed = new Date(date.toISOString());
        expect(reconstructed.getTime()).toBe(date.getTime());
      }),
      { numRuns: 100 },
    );
  });
});


/**
 * Feature: chat-persistence, Property 7: Inclusión de statusCode en errores del servicio
 *
 * **Validates: Requirement 10.5**
 *
 * For any backend error response with a numeric `statusCode` (4xx or 5xx),
 * the `ChatServiceError` thrown by `ChatService` must include a `statusCode`
 * property whose value matches exactly the status code from the response.
 */

/** Arbitrary that generates HTTP error status codes in the 4xx and 5xx ranges */
const httpErrorStatusCodeArb = fc.oneof(
  fc.integer({ min: 400, max: 499 }),
  fc.integer({ min: 500, max: 599 }),
);

describe('Feature: chat-persistence, Property 7: Inclusión de statusCode en errores del servicio', () => {
  it('ChatServiceError includes the exact statusCode from the backend error response', async () => {
    await fc.assert(
      fc.asyncProperty(httpErrorStatusCodeArb, async (statusCode) => {
        // Create a mock AppSyncEventsService that returns an error response with the generated statusCode
        const mockAppSyncService = {
          publishWithResponse: async () => ({ statusCode }),
        } as unknown as AppSyncEventsService;

        const chatService = new ChatService(mockAppSyncService);

        // Call a CRUD method and expect it to throw
        try {
          await chatService.listConversations('test-user');
          // If we reach here, the method did not throw — fail the test
          expect.fail('Expected ChatServiceError to be thrown');
        } catch (error: unknown) {
          // Verify the error is a ChatServiceError
          expect(error).toBeInstanceOf(ChatServiceError);

          const serviceError = error as ChatServiceError;

          // Verify the statusCode matches exactly
          expect(serviceError.statusCode).toBe(statusCode);

          // Verify the error has a non-empty message
          expect(serviceError.message).toBeTruthy();

          // Verify the error name
          expect(serviceError.name).toBe('ChatServiceError');
        }
      }),
      { numRuns: 100 },
    );
  });
});
