"""Production travel agent on Amazon Bedrock AgentCore Runtime.

DynamoDB variant: replaces the Valkey-based production_agent.py.
Cache infrastructure is a single DynamoDB table (no VPC required).
All configuration comes from SSM Parameter Store (/dynamodb-cache/*).

Same two-level cache design as the Valkey version:
  Level 1 (response cache)  — SemanticResponseCache from dynamodb_cache
  Level 2 (reasoning cache) — ReasoningCacheHook from dynamodb_cache

cache_mode payload options:
  both            (default) level 1 in front of level 2
  response-cache  level 1 only
  reasoning-cache level 2 only
"""

import hashlib
import json
import logging
import os
import time

import boto3
from bedrock_agentcore import BedrockAgentCoreApp

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = BedrockAgentCoreApp()

PARAM_PREFIX = "/dynamodb-cache"

_params = None
_hook = None
_agent_model = None
_response_cache = None

SYSTEM_PROMPT = (
    "You are a travel research assistant. Use the tools to gather real data: "
    "geocode_destination first when you need coordinates, climate_summary "
    "for real historical weather (to judge the best season), "
    "wikipedia_summary for visa policies or country overviews (article "
    "titles like 'Visa policy of Japan'), and search_flights for prices. "
    "If a tool returns 'not found' or an error, do NOT retry it with "
    "variations more than once — answer with what you have and say what "
    "is missing. Maximum 4 sentences, plain text only (no XML tags, no "
    "<thinking>), in the user's language."
)


def _get_params() -> dict:
    global _params
    if _params is None:
        ssm = boto3.client("ssm")
        params = {}
        paginator = ssm.get_paginator("get_parameters_by_path")
        for page in paginator.paginate(Path=PARAM_PREFIX, Recursive=True):
            for p in page["Parameters"]:
                params[p["Name"].removeprefix(f"{PARAM_PREFIX}/")] = p["Value"]
        missing = {"table-name", "vector-index-name", "entry-type-gsi-name",
                   "agent-model-id"} - params.keys()
        if missing:
            raise RuntimeError(f"SSM contract incomplete, missing: {missing}")
        _params = params
        os.environ.setdefault("EMBEDDING_MODEL_ID", params.get("embedding-model-id", ""))
        os.environ.setdefault("DUFFEL_SECRET_ARN", params.get("duffel-secret-arn", ""))
    return _params


def _get_hook():
    global _hook
    if _hook is None:
        from dynamodb_cache import ReasoningCacheHook

        params = _get_params()
        ddb = boto3.client("dynamodb")
        _hook = ReasoningCacheHook(
            ddb_client=ddb,
            table_name=params["table-name"],
            vector_index=params["vector-index-name"],
            entry_type_gsi=params["entry-type-gsi-name"],
            threshold=0.85,
            ttl=86400,
        )
    return _hook


def _get_response_cache():
    global _response_cache
    if _response_cache is None:
        from dynamodb_cache import SemanticResponseCache

        params = _get_params()
        prompt_hash = hashlib.md5(SYSTEM_PROMPT.encode(), usedforsecurity=False).hexdigest()[:8]
        _response_cache = SemanticResponseCache(
            ddb_client=boto3.client("dynamodb"),
            table_name=params["table-name"],
            vector_index=params["vector-index-name"],
            # Suffix #agentcore scopes entries so this agent never serves answers
            # generated by the demo Lambdas in stack 01.
            model_id=params["agent-model-id"] + "#agentcore",
            threshold=0.85,
            ttl=86400,
            prompt_hash=prompt_hash,
        )
    return _response_cache


def _rewrite_cached(question: str, cached_answer: str) -> tuple[str, dict]:
    from strands import Agent

    rewriter = Agent(
        model=_agent_model,
        system_prompt=(
            "Rewrite the VERIFIED ANSWER so it directly answers the user's "
            "question. CRITICAL: your entire reply MUST be in the same "
            "language the QUESTION is written in — translate the answer if "
            "needed. Keep every fact exactly as given; add nothing, "
            "contradict nothing. Maximum 3 sentences, plain text."
        ),
    )
    result = rewriter(f"QUESTION: {question}\nVERIFIED ANSWER: {cached_answer}")
    return str(result), dict(result.metrics.accumulated_usage)


_ES_MARKERS = {"que", "necesito", "para", "cuando", "cual", "como", "donde",
               "el", "la", "los", "las", "un", "una", "es", "si", "de", "mi"}
_EN_MARKERS = {"the", "what", "when", "which", "how", "where", "do", "does",
               "need", "is", "are", "a", "an", "to", "for", "my", "i"}


def _language_differs(question: str, cached_answer: str) -> bool:
    def score(text):
        words = set(text.lower().split())
        return len(words & _ES_MARKERS) - len(words & _EN_MARKERS)
    return (score(question) > 0) != (score(cached_answer) > 0)


def _clean_answer(text: str) -> str:
    import re
    if "<answer>" in text:
        text = text.split("<answer>", 1)[1].split("</answer>", 1)[0]
    text = re.sub(r"<thinking>.*?(</thinking>|$)", "", text, flags=re.S)
    return text.strip()


@app.entrypoint
def invoke(payload):
    question = (payload.get("prompt") or "").strip()
    if not question:
        return {"error": "payload must include a 'prompt' string"}
    cache_mode = payload.get("cache_mode", "both")
    use_level1 = cache_mode in ("both", "response-cache")
    use_level2 = cache_mode in ("both", "reasoning-cache")

    started = time.time()

    from strands import Agent
    from strands.models import BedrockModel
    from tools import ALL_TOOLS

    global _agent_model
    params = _get_params()
    if _agent_model is None:
        _agent_model = BedrockModel(model_id=params["agent-model-id"])

    hook = None
    response_cache = None
    try:
        hook = _get_hook()
        response_cache = _get_response_cache()
    except Exception:
        logger.exception("cache unavailable, running without it")

    flow = []
    if response_cache and use_level1:
        flow.append({"step": "response_lookup", "store": "dynamodb",
                     "detail": "semantic KNN over past answers"})
        hit = response_cache.lookup(question)
        if hit:
            flow.append({"step": "response_hit", "kind": "hit",
                         "detail": f"similarity {hit['similarity']} — agent loop SKIPPED"})
            answer = hit["answer"]
            source = "cache"
            rewrite_tokens = 0
            needs_rewrite = not hit["prompt_current"] or (
                hit["similarity"] < 0.999
                and _language_differs(question, hit["answer"])
            )
            if needs_rewrite:
                try:
                    answer, rewrite_usage = _rewrite_cached(question, answer)
                    rewrite_tokens = rewrite_usage.get("totalTokens", 0)
                    if not hit["prompt_current"]:
                        response_cache.refresh(hit["entry_id"], answer)
                    source = "cache-rewrite"
                    flow.append({"step": "rewrite", "kind": "hit",
                                 "detail": "verified answer adapted to this question"})
                except Exception:
                    logger.exception("rewrite failed, serving verbatim")
            tokens_saved = max(0, hit["tokens_saved"] - rewrite_tokens)
            response = {
                "answer": answer,
                "result": answer,
                "source": source,
                "similarity": hit["similarity"],
                "tokens_saved": tokens_saved,
                "cycles": 0,
                "usage": {"totalTokens": rewrite_tokens},
                "plan_hint_used": False,
                "tool_cache_hits": 0,
                "tool_executions": 0,
                "flow": flow,
                "latency_ms": int((time.time() - started) * 1000),
            }
            logger.info(json.dumps({k: v for k, v in response.items() if k not in ("answer", "result")}))
            return response
        flow.append({"step": "response_miss", "kind": "miss",
                     "detail": "no similar answer — running the agent loop"})

    agent = Agent(
        model=_agent_model,
        system_prompt=SYSTEM_PROMPT,
        tools=ALL_TOOLS,
        hooks=[hook] if (hook and use_level2) else [],
    )
    result = agent(question)

    usage = dict(result.metrics.accumulated_usage)
    stats = dict(hook.stats) if (hook and use_level2) else {}
    baseline = stats.get("cold_baseline_tokens", 0)
    tokens_saved = max(0, baseline - usage.get("totalTokens", 0)) if baseline else 0

    answer = _clean_answer(str(result))

    if hook and use_level2:
        flow.extend(getattr(hook, "flow", []))
    if response_cache and use_level1:
        response_cache.store(question, answer, usage)
        flow.append({"step": "response_stored", "kind": "store", "store": "dynamodb",
                     "detail": "answer cached for repeated/paraphrased questions"})

    response = {
        "answer": answer,
        "result": answer,
        "source": "agent",
        "tokens_saved": tokens_saved,
        "cycles": result.metrics.cycle_count,
        "usage": usage,
        "plan_hint_used": stats.get("plan_hint", False),
        "tool_cache_hits": stats.get("tool_cache_hits", 0),
        "tool_executions": stats.get("tool_executions", 0),
        "stale_served": stats.get("stale_served", 0),
        "flow": flow,
        "latency_ms": int((time.time() - started) * 1000),
    }
    logger.info(json.dumps({k: v for k, v in response.items() if k not in ("answer", "result")}))
    return response


if __name__ == "__main__":
    app.run()
